#!/bin/bash
case "`lsb_release -is`" in
     Ubuntu)
          rm -Rf ~/rl.txt
          lsb_release -r >> ~/rl.txt
          sed -ri 's/Release://g' ~/rl.txt
          sed -ri 's/   //g' ~/rl.txt
          vr=$(cat ~/rl.txt)
          vx=$(lsb_release -r)

          if [ "$vx" == "Release:	14.04" ]; then
          
             apt-get update; apt-get upgrade -y
             apt-get install build-essential lshw ruby git nano curl zip unzip python -y
             cd /opt
             wget https://github.com/busyloop/lolcat/archive/master.zip
             unzip master.zip
             rm -Rf master.zip
             cd lolcat-master/
             gem install lolcat
             cd /bin
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/bin/ubuntu/raws
             chmod +x raws
             clear
             cd /usr/local
             mkdir raws/
             cd raws/
             mkdir ubuntu/
             cd ubuntu/
             clear
             echo "Downloading Scripts..."
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/rv
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/st.py
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/si
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/ahost
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/help
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/imysql
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/yt
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/bye
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/update
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/env
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/inode
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/inginx
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/nhost
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/vnc
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/iapache
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/adel
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/ubuntu/ndel
             echo "Done..."
             sleep 3
             chmod +x *
             cd /usr/local/raws/
             curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/usr/local/raws/check
             chmod +x check
             clear
             raws -v
              
          else
              echo "I'm Sorry We Don't Support Ubuntu $vr !"
          fi
          rm -Rf ~/rl.txt
     ;;
     CentOS)
             echo "Coming Soon"
             exit
     ;;
     Debian)
             echo "Coming Soon"
             exit
     ;;
esac
