#!/bin/bash
# |============================================================|
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|
# | RAWS - SIMPLE LINUX CLI HELPER!
# | https://github.com/theraw/raws
# |============================================================|
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|
# | LOAD "STORE".
# source="`curl -s https://raw.githubusercontent.com/theraw/source/master/source`"
# sourceUser="`curl -s https://raw.githubusercontent.com/theraw/source/master/sourceUser`"
# Project="raws"
# export SOURCE=$source
# export SOURCEUSER=$sourceUser
# export PROJECT=$Project
export GET="raw.githubusercontent.com/theraw/raws/master"
# |============================================================|
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Removing if is already installed.                          |
# |============================================================|
rV() {
       if [ -d "/usr/local/raws" ]; then
          echo "Raws already installed detected!" | lolcat -a -s 100;
          echo "Removing..." | lolcat -a -s 100;
          rm -Rf /usr/local/raws
          rm -Rf /bin/raws
          rm -Rf /ssl
          echo "Done." | lolcat -a -s 100;
          clear
       fi
}
# |============================================================|
# | Check if we're root.                                       |
# |============================================================|
rT() {
       if [ "$(whoami)" != "root" ]
       then
           echo "You need to login as root to use this script! Sorry!";
           exit 1
       fi
}
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Updating System.                                           |
# |============================================================|
uP() {
       echo "Updating System!..."
       apt-get update -y
       apt-get upgrade -y
       apt-get dist-upgrade -y
       apt-get autoremove -y
       apt-get autoremove -y
       apt-get autoclean -y
       echo "Done."
       clear
       echo "Done."
       sleep 3
}
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Checking OS.                                               |
# |============================================================|
OS() {
       if [ "$(grep DISTRIB_CODENAME /etc/*-release | awk -F '=' '{print $2}')" != "trusty" ]
       then
           echo "Seems like your system isn't Ubuntu 14.04!"
           echo "If so we can't install raws there!"
           echo "If Your OS is Ubuntu 14.04 And Raws Fail, Then Please Report it on github issues!"
           exit 1
       fi
}
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Installing needed packs.                                   |
# |============================================================|
deP() {
       echo "Installing Needed Packs!..."
       sleep 5
       apt-get install build-essential bc systemd-services lshw ruby git nano curl zip unzip python sudo -y
       apt-get install software-properties-common python-software-properties -y
       apt-get install -y language-pack-en-base
       set LC_ALL=en_US.UTF-8; export LC_ALL=en_US.UTF-8
       gem install lolcat
       echo "Done." | lolcat -a -s 100;
       clear
       echo "Done." | lolcat -a -s 100;
       sleep 3
}
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Installing LetsEncrypt in case if is needed.               |
# |============================================================|
ssl() {
       # In case of update!
       if [ -e /ssl/dh2048.pem ]
       then
           echo "DHPARAM ALREADY GENERATED!"
       else
           mkdir /ssl
           apt-get install openssl -y
           git clone https://github.com/letsencrypt/letsencrypt
           mv letsencrypt /ssl
           cd /ssl/letsencrypt
           ./letsencrypt-auto --help
           ./certbot-auto --help
           #openssl dhparam -out /ssl/dh2048.pem -outform PEM -2 2048
           curl -s https://raw.githubusercontent.com/theraw/raws/master/static/dh2048.pem > /ssl/dh2048.pem
           clear
       fi
}
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Installing Raws.                                           |
# |============================================================|
R() {
       clear
       echo "Installing RAWS!..." | lolcat -a -s 100;
       cd /bin
       curl -s -O https://$GET/bin/ubuntu/raws
       chmod +x raws
       cd /usr/local
       mkdir -p raws/ubuntu
       cd /usr/local/raws/ubuntu
       curl -s -O https://$GET/usr/local/raws/ubuntu/rv
       curl -s -O https://$GET/usr/local/raws/ubuntu/st.py
       curl -s -O https://$GET/usr/local/raws/ubuntu/si
       curl -s -O https://$GET/usr/local/raws/ubuntu/ahost
       curl -s -O https://$GET/usr/local/raws/ubuntu/help
       curl -s -O https://$GET/usr/local/raws/ubuntu/imysql
       curl -s -O https://$GET/usr/local/raws/ubuntu/yt
       curl -s -O https://$GET/usr/local/raws/ubuntu/bye
       curl -s -O https://$GET/usr/local/raws/ubuntu/update
       curl -s -O https://$GET/usr/local/raws/ubuntu/env
       curl -s -O https://$GET/usr/local/raws/ubuntu/inode
       curl -s -O https://$GET/usr/local/raws/ubuntu/inginx
       curl -s -O https://$GET/usr/local/raws/ubuntu/nhost
       curl -s -O https://$GET/usr/local/raws/ubuntu/vnc
       curl -s -O https://$GET/usr/local/raws/ubuntu/iapache
       curl -s -O https://$GET/usr/local/raws/ubuntu/adel
       curl -s -O https://$GET/usr/local/raws/ubuntu/ndel
       curl -s -O https://$GET/usr/local/raws/ubuntu/iapache-new
       curl -s -O https://$GET/usr/local/raws/ubuntu/gen-ssl
       curl -s -O https://$GET/usr/local/raws/ubuntu/isql
       chmod +x *
       cd /usr/local/raws/
       curl -s -O https://$GET/usr/local/raws/check
       chmod +x check
       echo "Done." | lolcat -a -s 100;
       sleep 3
       clear
       raws -v
}
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|

# |============================================================|
# | Then Start!                                                |
# |============================================================|
if [ "$1" == 'INSTALL' ]; then
        rV; rT; uP; OS; deP; ssl; R;
   else
        echo "Please Use The Command As iT iS On Github.!"
        echo "Bye."
fi
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# |============================================================|
