#!/bin/bash
#This isn't for currently version of raws.
#I'm wroting this for new version.
echo -n "1. Removed .sh extension."
echo -n "2. Add Better Way to install."

echo -n "3. NEW : raws switch   | Turn Your Ubuntu 14.04 Server Into Desktop."
echo -n "4. NEW : raws inginx   | Install Nginx And Php5.6-fpm."
echo -n "5. NEW : raws nhost    | Create Vhost Based On Nginx."
echo -n "6. NEW : raws inode    | Install NodeJS Latest Stable."
echo -n "7. NEW : raws idocker  | Install Docker."
echo -n "8. NEW : raws ivagrant | Install Vagrant."

echo -n "9. FIXED : raws info."
echo -n "10. FIXED : raws update."

echo -n "11. UPDATED : Everything."

echo -n "Currently Raws Version 1.0"
