#!/bin/sh

# Uncomment the following two lines for normal desktop:
 unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &

#export XKL_XMODMAP_DISABLE=1
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS
#gnome-session --session=ubuntu -geometry 1024x768 -ls -title "$VNCDESKTOP Desktop" &

metacity &
gnome-settings-daemon &
gnome-panel &
