#!/bin/sh
unset SESSION_MANAGER

gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &

#HACK!!
# if you want to recover theme, icons or anything you can simply do
# Login from putty and stop vnc. like, vncserver -kill :1
# rm -Rf ~/.config/dconf/user
# start vnc then and you'll se everything is like in begin.
