#!/bin/sh

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &

gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &

#HACK!!
# if you want to recover theme, icons or anything you can simply do
# Login from putty and stop vnc. like, vncserver -kill :1
# rm -Rf ~/.config/dconf/user
# start vnc then and you'll se everything is like in begin.
