#!/bin/bash

if [ "$1" == 'adel' ] && [ "$2" ]; then
   rm -Rf /hostdata/$2
   sudo a2dissite $2
   rm -Rf /etc/apache2/sites-available/$2.conf
   service apache2 reload
   clear
   echo -e "||=======================================================||" | lolcat -a -s 100;
   echo -e "||=======================================================||" | lolcat -a -s 100;
   echo -e "||======|| R.I.P =>| $2                                    " | lolcat -a -s 100;
   echo -e "||=======================================================||" | lolcat -a -s 100;
   echo -e "||=======================================================||" | lolcat -a -s 100;
fi
