#!/bin/bash

check() {
        if [ "$(whoami)" != "root" ]
           then
               echo "You need to login as root to use raws gen-ssl! Sorry!" | lolcat -a -s 100;
               exit 1
        fi
        if [ -d "/etc/letsencrypt/live/$1" ]; then
          echo "Looks like You Already Have Generate A SSL For $1!" | lolcat -a -s 100;
          echo "Sorry We Can't Genereate A SSL For A Domain Which Already Have One!" | lolcat -a -s 100;
          exit 1
        fi
}

genit() {
        service nginx stop
        service apache2 stop
        cd /ssl/letsencrypt
        ./letsencrypt-auto --help
        ./certbot-auto --help
        clear
        ./certbot-auto certonly --standalone --email $2 -d $1
        mkdir -p /hostdata/$2/ssl
        ln -s /etc/letsencrypt/archive/$2/* /hostdata/$2/ssl/
        clear
}

if [ "$1" == 'gen-ssl' ] && [ "$2" ] && [ "$3" ]; then
      check $2; genit $2 $3;
      clear
      echo "Certificate Is Generated And Stored At" | lolcat -a -s 100;
      echo "/hostdata/$2/ssl/fullchain.pem" | lolcat -a -s 100;
      echo "/hostdata/$2/ssl/privkey.pem" | lolcat -a -s 100;
      echo "As symlink. Real path is at /etc/letsencrypt/archive/$2/" | lolcat -a -s 100;
      echo "Use your crt and privkey in vhost conf and start your webserver!" | lolcat -a -s 100;
      echo "We've Create a ssl cert only for '$2' you can use raws to create more ex 'raws gen-ssl email@ex.com www.$2'" | lolcat -a -s 100;
fi
