#!/bin/bash

check() {
        if [ "$(whoami)" != "root" ]
           then
               echo "You need to login as root to use raws gen-ssl! Sorry!" | lolcat -a -s 100;
               exit 1
        fi
        if [ -d "/etc/letsencrypt/live/$1" ]; then
          echo "Looks like You Already Have Generate A SSL For $1!" | lolcat -a -s 100;
          echo "Sorry We Can't Genereate A SSL For A Domain Which Already Have One!" | lolcat -a -s 100;
          exit 1
        fi
}

genit() {
        service nginx stop
        service apache2 stop
        /ssl/letsencrypt/letsencrypt-auto certonly --standalone -d $1 -d www.$1
        mkdir -p /hostdata/$1/ssl
        cp /ssl/dh2048.pem /hostdata/$1/ssl/
        cp /etc/letsencrypt/live/$1/* /hostdata/$1/ssl/
        clear
}

if [ "$1" == 'gen-ssl' ] && [ "$2" ]; then
      check $2; genit $2;
      clear
      echo -e "Certificate Is Generated And Stored At" | lolcat -a -s 100;
      echo -e "/hostdata/$2/ssl/fullchain.pem" | lolcat -a -s 100;
      echo -e "/hostdata/$2/ssl/privkey.pem" | lolcat -a -s 100;
      echo -e "As symlink. Real path is at /etc/letsencrypt/archive/$2/" | lolcat -a -s 100;
      echo -e "Use your crt and privkey in vhost conf and start your webserver!" | lolcat -a -s 100;
fi
