#!/bin/bash


cd $!/public_html
wget https://github.com/TryGhost/Ghost/releases/download/1.9.1/Ghost-1.9.1.zip
unzip Ghost-1.9.1.zip
rm -Rf Ghost-1.9.1.zip

npm cache clean -f
npm install -g n
n 6.9.0
sudo ln -sf /usr/local/n/versions/node/6.9.0/bin/node /usr/bin/node
sudo ln -sf /usr/local/n/versions/node/6.9.0/bin/npm /usr/bin/npm
npm config set prefix
cd $!/public_html
npm install
nano core/server/config/env/
npm install -g knex-migrator
./node_modules/knex-migrator/bin/knex-migrator init
