#!/bin/bash

gci() {
      sudo apt-get update -y; sudo apt-get dist-upgrade -y; sudo apt-get install build-essential libssl-dev curl wget nano -y
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get update -y
      sudo apt-get autoremove -y; sudo apt-get update -y; sudo apt-get dist-upgrade -y;
      apt-get install gcc-4.9 g++-4.9 cpp-4.9 -y
      apt-get install gcc-4.9-locales g++-4.9-multilib libstdc++6-4.9-dbg gcc-4.9-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan1-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libquadmath0-dbg lib32stdc++6-4.9-dbg libx32stdc++6-4.9-dbg -y
      cd /usr/bin
      rm gcc g++ cpp
      ln -s gcc-4.9 gcc
      ln -s g++-4.9 g++
      ln -s cpp-4.9 cpp
      clear
}

j4v() {
      sudo apt-get install openjdk-7-jdk -y
      clear
}

c1s() {
      sudo apt-get update; apt-get upgrade -y
      sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32gcc1 screen wget git curl -y
      sudo apt-get install libgtk2.0-0:i386 libgdk-pixbuf2.0-0:i386 libfontconfig1:i386 libxrender1:i386 libx11-6:i386 libglib2.0-0:i386  libxft2:i386 libfreetype6:i386 libc6:i386 zlib1g:i386 libpng12-0:i386 libgcc1:i386 -y
      apt-get install libpulse-dev:i386 -y
      sudo apt-get install ia32-libs -y
      sudo apt-get install libssl0.9.8 -y
      sudo apt-get install lib32stdc++6 -y
      clear
}

c1s6() {
      mkdir -p /build/c/steam/cmd/
      cd /build/c/steam/cmd/
      curl -sqL 'https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz' | tar zxvf -
      ./steamcmd.sh +quit
      ./steamcmd.sh +login anonymous +force_install_dir /cs/ +app_set_config 90 mod cstrike +app_update 90 +app_update 90 +app_update 90 -beta beta validate +quit
      clear
}

c3() {
      mkdir -p ~/.steam/sdk32/
      cd ~/.steam/sdk32/
      ln -s /build/c/steam/cmd/linux32/steamclient.so .
}

c2() {
      cd /cs/
      rm -Rf engine_i486.so
      wget https://github.com/systemroot/raws-dev/raw/master/static/cs/re/engine_i486.so
      wget https://github.com/systemroot/raws-dev/raw/master/static/cs/re/swds.pdb
      chmod +x *
      clear
}

amx() {
      cd /cs/cstrike/
      wget https://github.com/systemroot/raws-dev/raw/master/static/cs/reamx/reamx.zip
      unzip reamx.zip
      rm -Rf reamx.zip
      clear
}

meta() {
      cd /cs/cstrike/
      mkdir -p addons/metamod/dlls/
      cd addons/metamod/dlls/
      wget https://github.com/systemroot/raws-dev/raw/master/static/cs/ad/metamod.so
      cd /cs/cstrike/addons/metamod/
      touch plugins.ini
      echo 'linux addons/amxmodx/dlls/amxmodx_mm_i386.so' > plugins.ini
      echo 'linux addons/reunion/reunion_mm_i386.so' >> plugins.ini
      cd /cs/cstrike
      rm -Rf liblist.gam
      wget https://raw.githubusercontent.com/systemroot/raws-dev/master/static/cs/txt/liblist.gam
      chmod +x liblist.gam
      clear
}

c1() {
      cd /cs/cstrike/
      wget https://raw.githubusercontent.com/systemroot/raws-dev/master/static/cs/75/reunion.cfg
      wget https://raw.githubusercontent.com/systemroot/raws-dev/master/static/cs/75/public/reunion_api.h
      chmod +x *
      mkdir -p /cs/cstrike/addons/reunion
      cd /cs/cstrike/addons/reunion
      wget https://github.com/systemroot/raws-dev/raw/master/static/cs/75/bin/Linux/reunion_mm_i386.so
      chmod +x reunion_mm_i386.so
      cd /cs/cstrike
      clear
}
