#!/bin/bash

#check..
if [ "$(whoami)" != "root" ]
then
    echo "You need to login as root to use raws iapache! Sorry!" | lolcat -a -s 100;
    exit 1
fi

if [ -d "/etc/apache2" ]; then
  echo "Looks like apache is already installed there!" | lolcat -a -s 100;
  echo "We'll remove it se we can make a clean install!" | lolcat -a -s 100;
  apt-get remove --purge apache2 -y
  apt-get autoremove -y
  apt-get autoclean -y
fi
if [ -d "/etc/php5" ]; then
  echo "Looks like Php5 is already installed there!" | lolcat -a -s 100;
  echo "We'll remove it se we can make a clean install!" | lolcat -a -s 100;
  apt-get remove --purge php5 php5-common -y
  apt-get autoremove -y
  apt-get autoclean -y
fi

update() {
        apt-get update -y; apt-get upgrade -y; apt-get dist-upgrade -y
        apt-get install build-essential libssl-dev curl nano wget git zip unzip -y
        apt-get install software-properties-common -y
        apt-get install python-software-properties -y
}

newphp() {
        sudo add-apt-repository ppa:ondrej/php -y
        apt-get update -y; apt-get upgrade -y
}

install() {
        apt-get install apache2 -y
        apt-get install apache2-utils -y
        apt-get install php5.6 php5.6-common -y
}

phpPacks() {
        apt-get install libapache2-mod-php5.6 php5.6-cgi php5.6-cli php5.6-phpdbg libphp5.6-embed php5.6-dev -y
        apt-get install php5.6-curl php5.6-gd php5.6-imap php5.6-intl php5.6-ldap hp5.6-mysql php5.6-pgsql -y
        apt-get install php5.6-pspell php5.6-recode php5.6-sqlite3 php5.6-sybase php5.6-tidy php5.6-json -y
        apt-get install php5.6-bz2 php5.6-mcrypt php5.6-odbc php5.6-readline php5.6-interbase hp5.6-xmlrpc -y
        apt-get install php5.6-enchant php5.6-gmp hp5.6-xsl php5.6-bcmath php5.6-mbstring php5.6-soap -y
        apt-get install php5.6-xml php5.6-zip php5.6-dba -y
}

reconf() {
m='
<Directory /hostdata/>
         Options +Indexes +FollowSymLinks -MultiViews
         AllowOverride None
         Require all granted
</Directory>
'
        echo "$m" >> /etc/apache2/apache2.conf
        cd /var/www/html; rm -Rf index.html
        curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/static/apache/index.html
        clear
        echo -n "Creating Host Dir..." | lolcat -a -s 100; mkdir /hostdata && chmod -R 755 /hostdata/ >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Enabling Mcrypt..." | lolcat -a -s 100; sudo php5enmod mcrypt >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Enabling Rewrite ..." | lolcat -a -s 100; sudo a2enmod rewrite >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Restarting Apache2..." | lolcat -a -s 100; service apache2 restart >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
}

mod() {
        clear
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
        echo -n "|||||| Apache2 & Php5.6 Installed! ||||||||" | lolcat -a -s 100;
        echo -n "|||||| To Host A Domain Execute -> ||||||||" | lolcat -a -s 100;
        echo -n "|||||| raws ahost example.com |||||||||||||" | lolcat -a -s 100;
        echo -n "|||||| Apache Vhost Dir Is /hostdata ||||||" | lolcat -a -s 100;
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
}

#Wait for..
if [ "$1" == 'iapache' ]; then
        update; newphp; install; phpPacks; reconf; mod;
fi
