#!/bin/bash

#check..
check() {
if [ "$(whoami)" != "root" ]
then
    echo "You need to login as root to use raws iapache! Sorry!" | lolcat -a -s 100;
    exit 1
fi

if [ -d "/etc/apache2" ]; then
  echo "Looks like apache is already installed there!" | lolcat -a -s 100;
  echo "We'll remove it so we can make a clean install!" | lolcat -a -s 100;
  apt-get remove --purge apache2 -y
  apt-get autoremove -y
  apt-get autoclean -y
fi
if [ -d "/etc/php5" ]; then
  echo "Looks like Php5 is already installed there!" | lolcat -a -s 100;
  echo "We'll remove it so we can make a clean install!" | lolcat -a -s 100;
  apt-get remove --purge php5 php5-common -y
  apt-get autoremove -y
  apt-get autoclean -y
fi
}

update() {
        clear
        echo "Starting... #Step 1." | lolcat -a -s 100;
        echo -n "Updating System..." | lolcat -a -s 100; apt-get update -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Ugrading System..." | lolcat -a -s 100; apt-get upgrade -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Ugrading System2..." | lolcat -a -s 100; apt-get dist-upgrade -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing Basic Packs..." | lolcat -a -s 100; apt-get install build-essential libssl-dev curl nano wget git zip unzip -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing PPA..." | lolcat -a -s 100; apt-get install software-properties-common -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing PPA2..." | lolcat -a -s 100; apt-get install python-software-properties -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Removing What Isn't Needed!..." | lolcat -a -s 100; apt-get autoremove -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
}

newphp() {
        clear
        echo "Starting... #Step 2." | lolcat -a -s 100;
        echo -n "Using php5.6 PPA..." | lolcat -a -s 100; sudo add-apt-repository ppa:ondrej/php -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Updating Repo!..." | lolcat -a -s 100; apt-get update -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Updating Repo2!..." | lolcat -a -s 100; apt-get upgrade -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        apt-get autoremove -y
}

install() {
        clear
        echo "Starting... #Step 3." | lolcat -a -s 100;
        echo -n "Installing Apache2..." | lolcat -a -s 100; apt-get install apache2 -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing Apache2-Dev..." | lolcat -a -s 100; apt-get install apache2-dev -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing Apache2-Utils..." | lolcat -a -s 100; apt-get install apache2-utils -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing php5.6..." | lolcat -a -s 100; apt-get install php5.6 php5.6-common -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
}

phpPacks() {
        clear
        echo "Starting... #Step 4." | lolcat -a -s 100;
        echo -n "Installing php5.6 Packs1..." | lolcat -a -s 100; apt-get install rrdtool libapache2-mod-php5.6 php5.6-cgi php5.6-cli php5.6-phpdbg libphp5.6-embed php5.6-dev -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing php5.6 Packs2..." | lolcat -a -s 100; apt-get install php5.6-rrd php5.6-curl php-pear php5.6-gd php5.6-imap php5.6-intl php5.6-ldap hp5.6-mysql php5.6-pgsql -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing php5.6 Packs3..." | lolcat -a -s 100; apt-get install php5.6-pspell php5.6-recode php5.6-sqlite3 php5.6-sybase php5.6-tidy php5.6-json -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing php5.6 Packs4..." | lolcat -a -s 100; apt-get install php5.6-bz2 php5.6-mcrypt php5.6-odbc php5.6-readline php5.6-interbase hp5.6-xmlrpc -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing php5.6 Packs5..." | lolcat -a -s 100; apt-get install php5.6-enchant php5.6-gmp hp5.6-xsl php5.6-bcmath php5.6-mbstring php5.6-soap -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Installing php5.6 Packs6..." | lolcat -a -s 100; apt-get install php5.6-xml php5.6-zip php5.6-dba -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Removing php7..." | lolcat -a -s 100; apt-get remove php7.1-common -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
}

reconf() {
        clear
        echo "Starting... #Step 5." | lolcat -a -s 100;
m='
<Directory /hostdata/>
         Options +Indexes +FollowSymLinks -MultiViews
         AllowOverride None
         Require all granted
</Directory>
'
        echo "$m" >> /etc/apache2/apache2.conf
        cd /var/www/html; rm -Rf index.html
        curl -s -O https://raw.githubusercontent.com/systemroot/raws-dev/master/static/apache/index.html
        echo -n "Creating Host Dir..." | lolcat -a -s 100; mkdir /hostdata && chmod -R 755 /hostdata/ >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Enabling Rewrite ..." | lolcat -a -s 100; sudo a2enmod rewrite >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
        echo -n "Restarting Apache2..." | lolcat -a -s 100; service apache2 restart >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
}

mod() {
        clear
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
        echo -n "|||||| Apache2 & Php5.6 Installed! ||||||||" | lolcat -a -s 100;
        echo -n "|||||| To Host A Domain Execute -> ||||||||" | lolcat -a -s 100;
        echo -n "|||||| raws ahost example.com |||||||||||||" | lolcat -a -s 100;
        echo -n "|||||| Apache Vhost Dir Is /hostdata ||||||" | lolcat -a -s 100;
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
        echo -n "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*" | lolcat -a -s 100;
}

#Wait for..
if [ "$1" == 'iapache-new' ]; then
        check; update; newphp; install; phpPacks; reconf; mod;
fi
