#!/bin/bash

idocker() {
          sudo apt-get update -y; apt-get upgrade -y; apt-get dist-upgrade -y
          sudo apt-get autoremove -y; apt-get autoclean -y
          
}

if [ "$1" == 'idocker' ]; then
   idocker
fi
