#!/bin/bash
iMySql() {
if [[ "`whoami`" == 'root' ]]; then
echo -e "Updating System..." | lolcat -a -s 100; apt-get update -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Ugrading System..." | lolcat -a -s 100; apt-get upgrade -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Installing Mysql..." | lolcat -a -s 100;
echo -e "Maybe you now will see some outputs thats because we won't put them on null place" | lolcat -a -s 100;
echo -e "so you will be able to wrote database mysql password directly! Stay Here To Wrote It!" | lolcat -a -s 100;
sleep 20
apt-get install mysql-server mysql-client phpmyadmin -y
clear
echo -e "Restarting Apache..." | lolcat -a -s 100; service apache2 restart >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
clear
echo -e "Work Done (:" | lolcat -a -s 100;
echo -e "You maybe like GUI MYSQL? Visit IP/phpmyadmin" | lolcat -a -s 100;
echo -e "Username is root and password is that which you wroted on installation steps!" | lolcat -a -s 100;
else 
   echo "Please Use This Command As Root!, You can do "sudo -i" to switch to root and re'run command :)" | lolcat -a -s 100;
fi
}
if [[ "$1" == 'imysql' ]]; then
   iMySql
fi
