#!/bin/bash
inode() {
clear
rm -Rf /usr/local/n/versions/node/*
clear
echo -e "Updating System..." | lolcat -a -s 100; sudo apt-get update -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Ugrading System..." | lolcat -a -s 100; sudo apt-get upgrade -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Needed Packs..." | lolcat -a -s 100; sudo apt-get install dnsutils build-essential git libssl-dev openssl nano wget curl -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Add Node Source..." | lolcat -a -s 100; curl -sL https://deb.nodesource.com/setup_4.x | sudo bash - >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Installing Node..." | lolcat -a -s 100; sudo apt-get install nodejs -y >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Node `node -v` installed" | lolcat -a -s 100
echo -e "We will install last stable version!" | lolcat -a -s 100
sleep 5
clear
echo -e "Clearing Cache..." | lolcat -a -s 100; npm cache clean -f >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
clear
echo -e "Installing n..." | lolcat -a -s 100; mkdir /tmp; cd /tmp; npm install -g n >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Installing Node 6.9.0..." | lolcat -a -s 100; n 6.9.0 >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
clear
echo -e "Updating node bin..." | lolcat -a -s 100; sudo ln -sf /usr/local/n/versions/node/6.9.0/bin/node /usr/bin/node >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Updating npm bin..." | lolcat -a -s 100; sudo ln -sf /usr/local/n/versions/node/6.9.0/bin/npm /usr/bin/npm >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
echo -e "Fixing Prefix..." | lolcat -a -s 100; npm config set prefix >> /tmp/out.txt; echo "Done." | lolcat -a -s 100;
sleep 5
clear
echo -e "Node `node -v` updated!" | lolcat -a -s 100
echo -e "Npm `npm -v` updated!" | lolcat -a -s 100
echo -e "Output /tmp/out.txt" | lolcat -a -s 100
}

if [ "$1" == 'inode' ]; then
   inode
fi
