#!/bin/bash

check() {
      
}

dp() {
      sudo apt-get update -y; sudo apt-get upgrade -y
      apt-get dist-upgrade -y; apt-get autoclean -y
      apt-get autoremove -y
      apt-get install build-essential libssl-dev curl nano wget git zip unzip -y
      
}

usr() {

}
