#!/bin/bash

mysql() {
         apt-get update; apt-get upgrade -y
         #apt-get install mysql-server mysql-client -y
}

admin() {
        cd /hostdata/default/
        wget https://files.phpmyadmin.net/phpMyAdmin/4.7.9/phpMyAdmin-4.7.9-all-languages.zip
        unzip phpMyAdmin-4.7.9-all-languages.zip; rm -Rf phpMyAdmin-4.7.9-all-languages.zip
        mv phpMyAdmin-4.7.9-all-languages/ phpmyadmin
        chown -R www-data:www-data phpmyadmin/
        chown -R www-data:www-data phpmyadmin/*
        cd /hostdata/default/phpmyadmin/sql/
        clear
        echo "============================================="
        echo "WE WILL IMPORT 'create_tables.sql' FILE INTO YOUR MYSQL SERVER"
        echo "AND SO IS NEEDED TO WROTE YOUR PASSWORD OF MYSQL SERVER"
        echo "PASSWORD IS SAFE EXECUTED COMMAND IS =>"
        echo "mysql -u root -p < create_tables.sql"
        echo "============================================="
        mysql -u root -p < create_tables.sql
        cd /hostdata/default/phpmyadmin/
}
conf() {
cd /hostdata/default/phpmyadmin/
wget https://raw.githubusercontent.com/theraw/raws/master/static/nginx/phpmyadmin.cconf
clear
mv phpmyadmin.cconf /hostdata/default/phpmyadmin/config.inc.php

echo "`date +%s | sha256sum | base64 | head -c 32 ; echo`" > /hostdata/default/phpmyadmin/key.key
chkey="`cat /hostdata/default/phpmyadmin/key.key`"
sed -i "s/changethekey/$chkey/" /hostdata/default/phpmyadmin/config.inc.php
}

if [[ "$1" == 'isql' ]]; then
   mysql; admin; conf;
   clear
   fpm restart
   service nginx restart
   echo "# ============================================= #" | lolcat -a -s 100;
   echo "# ============================================= #" | lolcat -a -s 100;
   echo "$ PhpMyAdmin And Mysql Installed!. " | lolcat -a -s 100;
   echo "$ You should see phpmyadmin live at" | lolcat -a -s 100;
   ip="`curl -s api.ipify.org`"
   echo "$ http://$ip/phpmyadmin " | lolcat -a -s 100;
   echo "$ phpmyadmin conf ====> " | lolcat -a -s 100;
   echo "$ /hostdata/default/phpmyadmin/config.inc.php" | lolcat -a -s 100;
   echo "# ============================================= #" | lolcat -a -s 100;
   echo "# ============================================= #" | lolcat -a -s 100;
   
fi
