#!/bin/bash

mysql() {
         apt-get update; apt-get upgrade -y
         #apt-get install mysql-server mysql-client -y
}

admin() {
        cd /hostdata/default/
        wget https://files.phpmyadmin.net/phpMyAdmin/4.7.0/phpMyAdmin-4.7.0-all-languages.zip
        unzip phpMyAdmin-4.7.0-all-languages.zip; rm -Rf phpMyAdmin-4.7.0-all-languages.zip
        mv phpMyAdmin-4.7.0-all-languages/ phpmyadmin
        chown -R www-data:www-data phpmyadmin/
        chown -R www-data:www-data phpmyadmin/*
        cd /hostdata/default/phpmyadmin/sql/
        mysql -u root -p < create_tables.sql
        cd /hostdata/default/phpmyadmin/
}
conf() {
cd /hostdata/default/phpmyadmin/
wget https://raw.githubusercontent.com/systemroot/raws-dev/master/static/nginx/phpmyadmin.cconf
clear
mv phpmyadmin.cconf /hostdata/default/phpmyadmin/config.inc.php

echo "`openssl rand -base64 32`" > /hostdata/default/phpmyadmin/key.key
chkey="`cat /hostdata/default/phpmyadmin/key.key`"
sed -i "s/changethekey/$chkey/" /hostdata/default/phpmyadmin/config.inc.php
}

if [[ "$1" == 'isql' ]]; then
   mysql; admin; conf;
   clear
   fpm restart
   service nginx restart
   echo "# ============================================= #" | lolcat -a -s 100;
   echo "# ============================================= #" | lolcat -a -s 100;
   echo "$ PhpMyAdmin And Mysql Installed!. " | lolcat -a -s 100;
   echo "$ You should see phpmyadmin live at" | lolcat -a -s 100;
   ip="`curl -s api.ipify.org`"
   echo "$ http://$ip/phpmyadmin " | lolcat -a -s 100;
   echo "$ phpmyadmin conf ====> " | lolcat -a -s 100;
   echo "$ /hostdata/default/phpmyadmin/config.inc.php" | lolcat -a -s 100;
   echo "# ============================================= #" | lolcat -a -s 100;
   echo "# ============================================= #" | lolcat -a -s 100;
   
fi
