#!/bin/bash
if [[ "$1" == 'sysinfo' ]];
then
clear
distro=$(cat /etc/issue.net)
lscpu | grep Architecture: > ~/x.txt
sed -ri 's/Architecture://g' ~/x.txt
sed -ri 's/          //g' ~/x.txt
echo "`hostnamectl | grep Virtualization`" > /tmp/virt
sed -ri 's/    //g' /tmp/virt
lscpu | grep MHz > ~/mhz.txt
sed -ri 's/CPU MHz://g' ~/mhz.txt
sed -ri 's/               //g' ~/mhz.txt
chmod +x ~/mhz.txt
chmod +x ~/x.txt
x=$(cat ~/x.txt)
cpu=$(grep -c processor /proc/cpuinfo)
virt=$(cat /tmp/virt)
ram=$(grep MemTotal /proc/meminfo | awk '{print $2}' | xargs -I {} echo "scale=4; {}/1024^2" | bc)
ck=$(cat ~/mhz.txt)
ip=$(curl -s https://api.ipify.org)
cd /usr/local/raws/ubuntu/
echo -n "We Are Testing Your Internet Speed Please Wait..." | lolcat -a -s 100; ./st.py > ~/speed.txt; echo "Done." | lolcat -a -s 100;
up=$(egrep "Upload:" ~/speed.txt)
down=$(egrep "Download" ~/speed.txt)
clear
echo -e "|-------------------------------------------|" | lolcat -a -s 100
echo -e "|**********|       ~SYSTEM~      |**********|" | lolcat -a -s 100
echo -e "|*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*|" | lolcat -a -s 100
echo -e "|**********| You Are Using.      |**********|" | lolcat -a -s 100
echo -e "|**********| $distro. |**********|" | lolcat -a -s 100
echo -e "|**********| $x.             |**********|" | lolcat -a -s 100
echo -e "|**********| With  : $cpu CPU/s.    |**********|" | lolcat -a -s 100
echo -e "|**********| Clock : $ck    |**********|" | lolcat -a -s 100
echo -e "|**********| RAM   : $ram MB.  |**********|" | lolcat -a -s 100
echo -e "|**********| $virt |*******|" | lolcat -a -s 100
echo -e "|-------------------------------------------|" | lolcat -a -s 100
echo -e "|-------------------------------------------|" | lolcat -a -s 100
echo -e "|**********|      ~NETWORK~      |**********|" | lolcat -a -s 100
echo -e "|*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*|" | lolcat -a -s 100
echo -e "|**********| IP : $ip |*********|" | lolcat -a -s 100
echo -e "|**********| $up |********|" | lolcat -a -s 100
echo -e "|**********| $down |******|" | lolcat -a -s 100
echo -e "|-------------------------------------------|" | lolcat -a -s 100
#Clear.
rm -Rf ~/x.txt
rm -Rf ~/mhz.txt
rm -Rf ~/speed.txt
fi
