#!/bin/bash
switch() {
sudo apt-get update; sudo apt-get upgrade -y; sudo apt-get dist-upgrade -y
sudo apt-get install build-essential libssl-dev curl nano wget git -y
sudo apt-get install ubuntu-desktop -y
sudo apt-get install gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal -y
sudo apt-get install vnc4server -y
vncserver
vncserver -kill :1
cd ~/.vnc/
rm -Rf xstartup
wget https://raw.githubusercontent.com/systemroot/raws-dev/master/static/vnc/xstartup
chmod +x xstartup
}

if [[ "$1" == "switch" ]]; then
   switch
   clear
   echo "Installation Done" | lolcat -a -s 100;
   echo "You now can start and connect to your server from vnc viewer!" | lolcat -a -s 100;
   echo "You can start VNC like" | lolcat -a -s 100;
   echo "vncserver -geometry 1920x1080"
   echo "Then connect from vnc viewer on serverip:5901"
fi
