#!/bin/bash
switch() {
          sudo apt-get update; sudo apt-get upgrade -y; sudo apt-get dist-upgrade -y
          sudo apt-get install build-essential libssl-dev curl nano wget git -y
          sudo apt-get install ubuntu-desktop -y
          sudo apt-get install gnome-panel gnome-session gnome-settings-daemon metacity nautilus gnome-terminal -y
          sudo apt-get install synaptic -y
          sudo apt-get install gparted -y
          sudo apt-get install vnc4server -y
          sudo apt-get install software-properties-common -y
          sudo apt-get install python3-software-properties -y
          sudo apt-get install python-software-properties -y
          sudo apt-get install unity-tweak-tool gnome-tweak-tool -y
          sudo apt-get install xfonts-100dpi xfonts-100dpi-transcoded xfonts-75dpi xfonts-75dpi-transcoded xfonts-base -y
          

          mkdir ~/work
          cd ~/work
          sudo add-apt-repository ppa:webupd8team/brackets -y
          sudo add-apt-repository ppa:noobslab/themes -y
          sudo add-apt-repository ppa:upubuntu-com/icons -y
          sudo add-apt-repository ppa:numix/ppa -y
          sudo add-apt-repository ppa:papirus/papirus -y
          sudo add-apt-repository ppa:teejee2008/ppa -y
          sudo apt-get update -y
          sudo apt-get install numix-bluish-theme -y
          sudo apt-get install superflat-icon-theme -y
          sudo apt-get install papirus-icon-theme -y
          sudo apt-get install flatabulous-theme -y
          sudo apt-get install conky-manager -y
          sudo apt-get install brackets -y
          sudo apt-get install numix-folders numix-icon-theme-circle numix-icon-theme-bevel numix-tools numix-plymouth-theme numix-wallpaper-aurora numix-icon-theme-square numix-wallpaper-lightbulb stylishdark-theme royal-gtk-theme numix-gtk-theme shimmer-themes -y
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update -y
          sudo apt-get install google-chrome-stable -y
          sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder -y
          sudo apt-get update -y
          sudo apt-get install simplescreenrecorder -y
          sudo apt-get install vlc -y
          sudo apt-get install vlc browser-plugin-vlc -y
          sed -i 's/geteuid/getppid/' /usr/bin/vlc
          sudo apt-get install filezilla -y
          sudo apt-get install leafpad -y
          sudo apt-get install zip unzip curl audacity youtube-dl id3v2 mplayer -y
          cd ~/work
          rm -Rf ~/work
          mkdir -p /tmp
          cd /tmp
          wget rarlab.com/rar/rarlinux-x64-5.1.1.tar.gz
          tar -xzvf rarlinux-x64-5.1.1.tar.gz
          cd rar
          make
          sudo make install
          
          dpkg-reconfigure lightdm
          gsettings set org.gnome.desktop.background show-desktop-icons true
          clear
          mkdir -p ~/.vnc
          cd ~/.vnc/
          rm -Rf xstartup
          wget https://raw.githubusercontent.com/systemroot/raws-dev/master/static/vnc/xstartup
          chmod +x xstartup
          cd /root/
          mkdir Desktop/
          cd Desktop/
          curl -s -O https://github.com/systemroot/raws-dev/raw/master/static/vnc/Space-Desktop.jpg
}

if [[ "$1" == "switch" ]]; then
   clear
   switch
   clear
   echo "Installation Done" | lolcat -a -s 100;
   echo "You now can start and connect to your server from vnc viewer!" | lolcat -a -s 100;
   echo "You can start VNC like" | lolcat -a -s 100;
   echo "vncserver -geometry 1920x1080"
   echo "Then connect from vnc viewer on serverip:5901"
   echo "Fist set a vnc password with command..."
   echo "vncpasswd"
fi
